RailsApp/config/routes.rb
TheCampusFeed::Application.routes.draw do

  get '/partials/:partialName' => 'partials#byName'

=begin
    scope '/api/v1', defaults: {format: :json} do
      shallow do
        get '/colleges/:id/image' => 'colleges#image'
        resources :colleges do
          get '/posts/byTag/:tagText' => 'posts#byTag'
          get '/posts/recent' => 'posts#recent'
          get '/posts/trending' => 'posts#trending'
          resource :posts do
            resources :comments do
              get 'votes/score' => 'votes#score'
              resources :votes do
              end
            end
          end
          get '/tags/trending' => 'tags#trending'
          resources :tags
        end
      end
    end
=end
    scope '/api/v1', defaults: {format: :json}, shallow_path: '/api/v1' do

      get '/minAndroidVersion' => 'versioner#android'
      get '/miniOSVersion' => 'versioner#ios'

      get '/comments/many' => 'comments#many'
      get '/posts/many' => 'posts#many'

      resources :images, only: [:create, :show]
      resources :comments, only: [:show]
      resources :flags, only: [:show]
      resources :votes, only: [:show, :destroy]
      resources :users, only: [:show]

      get '/posts/search/:searchText' => 'posts#search'
      get '/posts/search/:searchText/count' => 'posts#searchCount'
      get '/posts/count' => 'posts#count'
      get '/posts/byTag/:tagText' => 'posts#byTag'
      get '/posts/recent' => 'posts#recent'
      get '/posts/trending' => 'posts#trending'
      get '/posts/hidden' => 'posts#hidden'
      get '/posts/flagged' => 'posts#flagged'
      get '/posts/flagged/count' => 'posts#flagged_count'
      resources :posts do
        get '/comments/search/:searchText' => 'comments#search'
        get '/comments/search/:searchText/count' => 'comments#searchCount'
        get '/comments/count' => 'comments#count'
        resources :comments, except: [:show] do
          get 'votes/score' => 'votes#score'
          resources :votes, only: [:create, :score, :destroy]
          resources :flags
        end
        get 'votes/score' => 'votes#score'
        resources :votes
        resources :flags
      end

      get '/tags/trending' => 'tags#trending'
      resources :tags

      get '/colleges/:id/image' => 'colleges#image'
      get '/colleges/search/:searchText' => 'colleges#search'
      get '/colleges/search/:searchText/count' => 'colleges#searchCount'
      get '/colleges/count' => 'colleges#count'
      get '/colleges/trending' => 'colleges#trending'
      get '/colleges/listVersion' => 'colleges#listVersion'
      resources :colleges do

        get '/posts/byTag/:tagText' => 'posts#byTag'
        get '/posts/recent' => 'posts#recent'
        get '/posts/trending' => 'posts#trending'
        resources :posts do
          get '/comments/search/:searchText' => 'comments#search'
          get '/comments/search/:searchText/count' => 'comments#searchCount'
          get '/comments/count' => 'comments#count'
          resources :comments, except: [:show] do
            get 'votes/score' => 'votes#score'
            resources :votes, only: [:create, :score, :destroy]
            resources :flags
          end
          get 'votes/score' => 'votes#score'
          resources :votes
          resources :flags
        end

        get '/tags/trending' => 'tags#trending'
        resources :tags
      end

    end

=begin
      resources :users do
        get '/colleges/:id/image' => 'colleges#image'
        resources :colleges, only: [:index] do

          get '/posts/byTag/:tagText' => 'posts#byTag'
          get '/posts/recent' => 'posts#recent'
          get '/posts/trending' => 'posts#trending'
          resources :posts do
            resources :comments, except: [:show] do
              get 'votes/score' => 'votes#score'
              resources :votes, only: [:create]
            end
            get 'votes/score' => 'votes#score'
            resources :votes
          end

          get '/tags/trending' => 'tags#trending'
          resources :tags
        end

        resources :comments, only: [:show]

        get '/posts/byTag/:tagText' => 'posts#byTag'
        get '/posts/recent' => 'posts#recent'
        get '/posts/trending' => 'posts#trending'
        resources :posts do
          resources :comments, except: [:show] do
            get 'votes/score' => 'votes#score'
            resources :votes, only: [:create]
          end
          get 'votes/score' => 'votes#score'
          resources :votes
        end

        get '/tags/trending' => 'tags#trending'
        resources :tags
      end
    end
=end
    root to: 'static_pages#landing'
    get '/college/:id' => 'static_pages#webapp_college'
    get '/tag/:text' => 'static_pages#webapp_tag'
    get '/post/:id' => 'posts#show'

    get '/admin' => 'static_pages#admin'
    get '/landing' => 'static_pages#landing'
    get '/mobile' => 'static_pages#index'
    get '/stats' => 'static_pages#stats'
    get '/webapp' => 'static_pages#webapp'
    get '/landing' => 'static_pages#landing'

end

RailsApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  http_basic_authenticate_with :name => "admin", :password => ENV['ADMIN_PASSWORD'], only: :admin

  after_action :allow_iframe, only: :landing

  def index
  end

  def admin
  end

  def landing
  end

  def stats
  end

  def webapp
  end

  def webapp_college
  end

  def webapp_tag
  end

private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end

end

RailsApp/app/views/static_pages/admin.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body ng-app="cfeed">
<nav class="navbar navbar-default" id="default" role="navigation">
  <div class="absoluteFull" id="navBg" randombgpos>

  </div>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= fa_icon 'mortar-board' %><span class="light">The</span>Campus<span class="light">Feed</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#"><%= fa_icon 'file-text' %> Posts</a>
        </li>
        <li>
          <a href="#"><%= fa_icon 'university' %> Colleges</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon 'user' %>
            Admin<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%= admin_path %>"><%= fa_icon 'gears' %> Control Panel</a></li>
            <li><a href="<%= stats_path %>"><%= fa_icon 'dollar' %> Stat Panel</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="container">
  <h1>Control Panel</h1>

  <div class="col-md-12" ng-controller="SectionController">
    <accordion close-others="oneAtATime">

      <div ng-include ng-repeat="section in sections" src="section.template" is-open="section.isOpen">
      </div>

    </accordion>
  </div>
</div>
</body>
</html>

RailsApp/app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheCampusFeed</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
    <link rel="stylesheet" href="app.min.css">
    <style>
      .app-topbar{
        background-color: #33B5E5;
      }
    </style>
  </head>

  <body>
    <div class="app-page" data-page="home">
      <div class="app-topbar">
        <div class="app-title">TheCampusFeed</div>
        <div class="app-button right" id="postButton"><%= fa_icon 'pencil-square-o 3x' %></div>
      </div>
      <div class="app-content" id="postContent">
        <ul class="app-section app-list" id="postList">
          <label>Recent Posts</label>
        </ul>
        <div class="app-section" style="display:none;">
          <label id="loadingText">Loading</label>
        </div>
      </div>
    </div>

    <div class="app-page" data-page="page2">
      <div class="app-topbar">
        <div class="app-button left" data-back data-autotitle></div>
        <div class="app-title">Page 2</div>
      </div>
      <div class="app-content">
        Page 2 is lonely
      </div>
    </div>

    <script src="zepto.js"></script>
    <script src="app.min.js"></script>
    <script>

      App.controller('home', function (page) {
        // put stuff here
        $(page).find('#postButton').on('click', function(){
          console.log('asfd');
        });
      });

      App.controller('page2', function (page) {
        // put stuff here
      });
      
      App.populator('home', function (page) {
        var pageNum = 0;
        App.infiniteScroll($(page).find('#postList'), {loading: $(page).find('#loadingText')}, function (next) {
          pageNum++;
          $.getJSON('api/v1/posts?page='+pageNum+'&per_page=1',function(data){
            console.log(pageNum);
            // dynamically fetch data
            // add html elements to list
            var list = [];
            data.forEach(function(p){
              list.push($("<li><div>" + p.text + "</div></li>"));
            });
            next(list);
          });
        });
      });
      

      try {
        App.restore();
      } catch (err) {
        App.load('home');
      }
    </script>
  </body>
</html>

RailsApp/app/views/static_pages/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheCampusFeed</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="landing" ng-app="cfeed">
<div class="container-fluid" ng-controller="LandingCtrl">
  <div class="row">
    <div class="section col-md-12" id="title" randombgpos
         ng-class="{'col-md-12': options.post_selected.active == null, 'col-md-6': options.post_selected.active != null}">
      <div class="center">
        <%= image_tag "icon.png", height: 150 %> <br/>
        <%= image_tag "logo.png", height: 150 %>
        <progressbar class="progress-striped active" value="95" type="info" width="300">95% Complete</progressbar>
        <div id="description">
          <span>Launching soon on iOS, Android, and the web.</span><br/>
          <span>Follow us on twitter for updates: <a href="https://twitter.com/the_campus_feed">@The_Campus_Feed</a></span><br/>
        </div>
      </div>
    </div>
</div>

</body>
</html>

RailsApp/app/views/static_pages/stats.html.erb
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body ng-app="cfeed">
<nav class="navbar navbar-default" id="default" role="navigation">
  <div class="absoluteFull" id="navBg" randombgpos>

  </div>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= fa_icon 'mortar-board' %>College<span class="light">Feed</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown active">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="<%= admin_path %>">Control Panel</a></li>
            <li><a href="<%= stats_path %>">Stat Panel</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon 'user' %>
            Admin<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">My Posts</a></li>
            <li><a href="#">My Comments</a></li>
            <li class="divider"></li>
            <li><a href="#">Log Out</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="container">
  <h1>Stats Panel</h1>

  <div class="col-med-12" ng-controller="SectionController">

  </div>
</div>
</body>
</html>

RailsApp/app/views/static_pages/webapp.html.erb
<html>
<head>
</head>
<body class="webapp" ng-app="cfeed">
<nav class="navbar navbar-default navbar-fixed-top" id="default" role="navigation">
  <div class="absoluteFull" id="navBg" randombgpos>

  </div>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= fa_icon 'mortar-board' %><span class="light">The</span>Campus<span class="light">Feed</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#"><%= fa_icon 'file-text' %> Posts</a>
        </li>
        <li>
          <a href="#"><%= fa_icon 'university' %> Colleges</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="container-fluid" ng-controller="WebappCtrl">
  <div class="modal fade" id="getAppModal" tabindex="-1" role="dialog" aria-labelledby="Ge\tApp" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">App Only Action</h4>
        </div>
        <div class="modal-body">
          Sorry, you'll need to get our Android or iOS app to do that.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="sendEmailModal" tabindex="-1" role="dialog" aria-labelledby="SendEmail" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">Share this Post</h4>
        </div>
        <div class="modal-body">
          Send an email to yourself to view this post on your mobile device.
          <div class="form-field">
            <input type="email"/>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Submit</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-10" id="posts" infinite-scroll="atBottom()" masonry="{gutter:20, isFitWidth:false, isAnimatedFromBottom:true}" >
      <div class="card slide pointer masonry-brick" ng-repeat="post in posts.recentPosts" >
        <div class="card-background absoluteFull" randombgpos>
        </div>
        <div class="card-controls">
          <div class="button-container">
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-up" %></div></div>
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-down" %></div></div>
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "flag" %></div></div>
            <div class="button" data-toggle="modal" data-target="#sendEmailModal"><div class="button-text"><%= fa_icon "envelope" %></div></div>
          </div>
        </div>
        <div class="card-content">
          <div class="card-arrows">
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-up" %></div></div>
            {{post.vote_delta}}
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-down" %></div></div>
          </div>
          <h3 converttagstolinks="">{{post.text}}</h3>
          <img class="card-image" ng-src="{{post.image_uri}}" />
          <hr/>
          <div class="pull-left"><i collegenamefromid cid="{{post.college_id}}"></i></div>
          <div class="pull-right">
            <div class="badge">{{post.comment_count}}</div>
            <span class="comments-string">Comments</span></div>

          <div class="clearfix"></div>
          <hr/>
          <!--<div postcomments="5" postcollege="{{post.college_id}}" postid="{{post.id}}">
        </div>-->
        </div>
      </div>
    </div>
    <div class="sidebar">
      <div data-spy="affix" data-offset-top="0" data-offset-bottom="0">
        <div class="well">
          <h4>
            Trending Colleges
          </h4>
          <hr/>
          <div>
            <div ng-repeat="college in colleges.trendingColleges">
              <a href="college/{{college.id}}">{{college.name}}</a>
            </div>
          </div>

          <hr/>

          <h4>
            Trending Tags
          </h4>
          <hr/>
          <div class="tag-container">

            <div ng-repeat="tag in tags.trendingTags">
              <a href="tag/{{tag.text}}">#{{tag.text}}</a>
            </div>
          </div>
        </div>
        <div class="well">
          <h4>
            Get the App
          </h4>
          <hr/>
          <div>
            <a href="#">iOS</a>
            <a href="#">Android</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>

RailsApp/app/views/static_pages/webapp_college.html.erb
<html>
<head>
  <link rel="stylesheet" href="stylesheets/webapp.css">
</head>
<body ng-app="cfeed">
<nav class="navbar navbar-default navbar-fixed-top" id="default" role="navigation">
  <div class="absoluteFull" id="navBg" randombgpos>

  </div>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= fa_icon 'mortar-board' %>College<span class="light">Feed</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#"><%= fa_icon 'file-text' %> Posts</a>
        </li>
        <li>
          <a href="#"><%= fa_icon 'university' %> Colleges</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>
<div class="container-fluid" ng-controller="WebappCtrl">
  <div class="modal fade" id="getAppModal" tabindex="-1" role="dialog" aria-labelledby="GetApp" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">App Only Action</h4>
        </div>
        <div class="modal-body">
          Sorry, you'll need to get our Android or iOS app to do that.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="sendEmailModal" tabindex="-1" role="dialog" aria-labelledby="SendEmail" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title">Share this Post</h4>
        </div>
        <div class="modal-body">
          Send an email to yourself to view this post on your mobile device.
          <div class="form-field">
            <input type="email"/>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-success" data-dismiss="modal">Submit</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-4" id="posts" infinite-scroll="atBottom()">
      <div class="card slide pointer" ng-repeat="post in posts.recentPosts" ng-click="selectPost(post)" ng-class="{active: post.active}">
        <div class="card-background absoluteFull" randombgpos>
        </div>
        <div class="card-controls">
          <div class="button-container">
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-up" %></div></div>
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "arrow-down" %></div></div>
            <div class="button" data-toggle="modal" data-target="#getAppModal"><div class="button-text"><%= fa_icon "flag" %></div></div>
            <div class="button" data-toggle="modal" data-target="#sendEmailModal"><div class="button-text"><%= fa_icon "envelope" %></div></div>
          </div>
        </div>
        <div class="card-content">
          <h3 converttagstolinks="">{{post.text}}</h3>
          <hr/>
          <div class="pull-left"><i collegenamefromid cid="{{post.college_id}}"></i></div>
          <div class="pull-right">
            <div class="badge">{{post.comment_count}}</div>
            <span class="comments-string">Comments</span></div>

          <div class="clearfix"></div>
          <hr/>
          <div postcollege="{{post.college_id}}" postcomments="{{post.id}}">
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div data-spy="affix" data-offset-top="0" data-offset-bottom="0">
        <div class="well">
          <h4>
            Trending Colleges
          </h4>
          <hr/>
          <div>
            <div ng-repeat="college in colleges.trendingColleges">
              <a href="#">{{college.name}}</a>
            </div>
          </div>

          <hr/>

          <h4>
            Trending Tags
          </h4>
          <hr/>
          <div class="tag-container">

            <div ng-repeat="tag in tags.trendingTags">
              <a href="#">#{{tag.text}}</a>
            </div>
          </div>
        </div>
        <div class="well">
          <h4>
            Get the App
          </h4>
          <hr/>
          <div>
            <a href="#">iOS</a>
            <a href="#">Android</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>