config/routes.rb
Postfeed::Application.routes.draw do

  get '/partials/:partialName' => 'partials#byName'

=begin
    scope '/api/v1', defaults: {format: :json} do
      shallow do
        get '/colleges/:id/image' => 'colleges#image'
        resources :colleges do
          get '/posts/byTag/:tagText' => 'posts#byTag'
          get '/posts/recent' => 'posts#recent'
          get '/posts/trending' => 'posts#trending'
          resource :posts do
            resources :comments do
              get 'votes/score' => 'votes#score'
              resources :votes do
              end
            end
          end
          get '/tags/trending' => 'tags#trending'
          resources :tags
        end
      end
    end
=end
    scope '/api/v1', defaults: {format: :json}, shallow_path: '/api/v1' do

      resources :comments, only: [:show]
      resources :flags, only: [:show]

      get '/posts/search/:searchText' => 'posts#search'
      get '/posts/search/:searchText/count' => 'posts#searchCount'
      get '/posts/count' => 'posts#count'
      get '/posts/byTag/:tagText' => 'posts#byTag'
      get '/posts/recent' => 'posts#recent'
      get '/posts/trending' => 'posts#trending'
      resources :posts do
        get '/comments/search/:searchText' => 'comments#search'
        get '/comments/search/:searchText/count' => 'comments#searchCount'
        get '/comments/count' => 'comments#count'
        resources :comments, except: [:show] do
          get 'votes/score' => 'votes#score'
          resources :votes, only: [:create]
          resources :flags
        end
        get 'votes/score' => 'votes#score'
        resources :votes
        resources :flags
      end

      get '/tags/trending' => 'tags#trending'
      resources :tags

      get '/colleges/:id/image' => 'colleges#image'
      get '/colleges/search/:searchText' => 'colleges#search'
      get '/colleges/search/:searchText/count' => 'colleges#searchCount'
      get '/colleges/count' => 'colleges#count'
      resources :colleges do

        get '/posts/byTag/:tagText' => 'posts#byTag'
        get '/posts/recent' => 'posts#recent'
        get '/posts/trending' => 'posts#trending'
        resources :posts do
          get '/comments/search/:searchText' => 'comments#search'
          get '/comments/search/:searchText/count' => 'comments#searchCount'
          get '/comments/count' => 'comments#count'
          resources :comments, except: [:show] do
            get 'votes/score' => 'votes#score'
            resources :votes, only: [:create]
            resources :flags
          end
          get 'votes/score' => 'votes#score'
          resources :votes
          resources :flags
        end

        get '/tags/trending' => 'tags#trending'
        resources :tags
      end

    end

=begin
      resources :users do
        get '/colleges/:id/image' => 'colleges#image'
        resources :colleges, only: [:index] do

          get '/posts/byTag/:tagText' => 'posts#byTag'
          get '/posts/recent' => 'posts#recent'
          get '/posts/trending' => 'posts#trending'
          resources :posts do
            resources :comments, except: [:show] do
              get 'votes/score' => 'votes#score'
              resources :votes, only: [:create]
            end
            get 'votes/score' => 'votes#score'
            resources :votes
          end

          get '/tags/trending' => 'tags#trending'
          resources :tags
        end

        resources :comments, only: [:show]

        get '/posts/byTag/:tagText' => 'posts#byTag'
        get '/posts/recent' => 'posts#recent'
        get '/posts/trending' => 'posts#trending'
        resources :posts do
          resources :comments, except: [:show] do
            get 'votes/score' => 'votes#score'
            resources :votes, only: [:create]
          end
          get 'votes/score' => 'votes#score'
          resources :votes
        end

        get '/tags/trending' => 'tags#trending'
        resources :tags
      end
    end
=end
    root to: 'static_pages#index'

    get '/admin' => 'static_pages#admin'

end

app/models/flag.rb
class Flag < ActiveRecord::Base
  belongs_to :votable
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  before_action :set_flag, only: [:show, :edit, :update, :destroy]

  # GET /flags
  # GET /flags.json
  def index
    @flags = Flag.all
  end

  # GET /flags/1
  # GET /flags/1.json
  def show
  end

  # GET /flags/new
  def new
    @flag = Flag.new
  end

  # GET /flags/1/edit
  def edit
  end

  # POST /flags
  # POST /flags.json
  def create
    @flag = Flag.new(flag_params)

    respond_to do |format|
      if @flag.save
        format.html { redirect_to @flag, notice: 'Flag was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flag }
      else
        format.html { render action: 'new' }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flags/1
  # PATCH/PUT /flags/1.json
  def update
    respond_to do |format|
      if @flag.update(flag_params)
        format.html { redirect_to @flag, notice: 'Flag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flags/1
  # DELETE /flags/1.json
  def destroy
    @flag.destroy
    respond_to do |format|
      format.html { redirect_to flags_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flag
      @flag = Flag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flag_params
      params.require(:flag).permit(:votable_id)
    end
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/views/flags/_form.html.erb
<%= form_for(@flag) do |f| %>
  <% if @flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% @flag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :votable_id %><br>
    <%= f.text_field :votable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<h1>Editing flag</h1>

<%= render 'form' %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

app/views/flags/index.html.erb
<h1>Listing flags</h1>

<table>
  <thead>
    <tr>
      <th>Votable</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @flags.each do |flag| %>
      <tr>
        <td><%= flag.votable %></td>
        <td><%= link_to 'Show', flag %></td>
        <td><%= link_to 'Edit', edit_flag_path(flag) %></td>
        <td><%= link_to 'Destroy', flag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flag', new_flag_path %>

app/views/flags/new.html.erb
<h1>New flag</h1>

<%= render 'form' %>

<%= link_to 'Back', flags_path %>

app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Votable:</strong>
  <%= @flag.votable %>
</p>

<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>